name: macOS 11 Makefile

on:
  push:
    branches: [ OpenMPT-1.30 ]

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      run: brew update && brew install p7zip help2man doxygen autoconf-archive mpg123 libogg libvorbis portaudio flac libsndfile sdl2 && brew upgrade
    - name: setup parallel make
      run: echo "MAKEFLAGS=-j$(sysctl -n hw.ncpu)" >> $GITHUB_ENV
    - name: make
      run: make STRICT=1 FORCE_DEPS=1
    - name: make check
      run: make STRICT=1 FORCE_DEPS=1 check
