name: OpenBSD 7.2 Makefile

on:
  push:
    branches: [ OpenMPT-1.30 ]
  pull_request:
    branches: [ OpenMPT-1.30 ]

jobs:
  build:

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3
    - uses: cross-platform-actions/action@v0.11.0
      with:
        architecture: x86_64
        hypervisor: xhyve
        operating_system: openbsd
        version: '7.2'
        shell: bash
        run: |
          sudo pkg_add subversion p5-XML-XPath git mawk gmake pkgconf autoconf autoconf-archive automake libtool libltdl help2man doxygen mpg123 libogg libvorbis flac libsndfile pulseaudio portaudio-svn sdl2
          gmake -j$(sysctl -n hw.ncpu) STRICT=1 VERBOSE=1 AUTO_DEPS=1
          gmake -j$(sysctl -n hw.ncpu) STRICT=1 VERBOSE=1 AUTO_DEPS=1 check
